### ISSUE TITLE
Joss Review: Regarding the functionality of the Package

### ISSUE THREAD

**Issue by sandeshkatakam** [dirmeier/surjectors#25]
I have been trying to install and use the surjectors package, but I am facing a problem with importing sub-modules from surjectors. Specifically, I got this Module Not Found Error: surjectors.nn is not available

Can you guide me on how to work around this?\

Link to the Review Thread: https://github.com/openjournals/joss-reviews/issues/6188

**Comment by dirmeier** [comment]
Hey, thanks for testing. How did you try installing the package?

**Comment by dirmeier** [comment]
Pinging @sandeshkatakam

**Comment by dirmeier** [comment]
Please see #26

**Comment by sandeshkatakam** [comment]
Hey sorry, I had an emergency and couldn't check the updates on this thread.
I'll look at this ASAP
